### ISSUE TITLE
GameTracer.cu Sampler issue

### ISSUE THREAD

**Issue by iscaswcm** [hhergeth/CudaTracerLib#14]
When compiling CudaTracerLib On CentOS 7.1, I got the following error:

/home/wcm/CudaTracerLib-related/CudaTracerLib.ori/Integrators/PseudoRealtime/GameTracer.cu(97): error: no instance of function template "CudaTracerLib::PathTrace" matches the argument list
            argument types are: (CudaTracerLib::NormalizedT<CudaTracerLib::Ray, void>, CudaTracerLib::SequenceSampler, int, int)

1 error detected in the compilation of "/tmp/tmpxft_00005d96_00000000-6_GameTracer.cpp1.ii".
CMake Error at CudaTracerLib_generated_GameTracer.cu.o.cmake:260 (message):
  Error generating file
  /home/wcm/CudaTracerLib-related/build/CMakeFiles/CudaTracerLib.dir/Integrators/PseudoRealtime/./CudaTracerLib_generated_GameTracer.cu.o

@hhergeth, I think the error came from template<bool DIRECT> CUDA_FUNC_IN Spectrum PathTrace(NormalizedT<Ray>& r, Sampler& rnd, int maxPathLength, int rrStartDepth).
Currently, I just rm Integrators/PseudoRealtime/GameTracer.cu Integrators/PseudoRealtime/GameTracer.h, Compiling is OK.

**Comment by hhergeth** [comment]
Thank you very much for letting me know about this!
After the CUDA 9.0 update I forgot to check whether it compiles fine under linux.

I pushed 3dc123855554e9616d08c156a605ea5ec682f85f which should fix all of these issues (there were a couple more with using functions from std::)
